### ISSUE TITLE
Cannot connect to ES in AWS

### ISSUE THREAD

**Issue by agntdv** [AntonShuvaev/elasticsearch4idea#122]
**Describe the bug**
I cannot connect to Elasticsearch in AWS using .aws/credentials file, while it works fine when connecting in Postman.

**Steps to reproduce**
1. Open up Elasticsearch client
2. In General tab specify connect to Elasticsearch and the URL to ES cluster
3. In AWS tab specify "Managed Cluster" (tried "Serverless" as well), relevant region, "Profile from credentials file", path to Credentials file, profile name in Profile
4. Clicking "Test connection" gives "Connection test failed: org.apache.http.client.ClientProtocolException", trying the same in Postman - all is ok

**Expected behavior**

**Environment information:**
- OS: Windows 11 Ent
- IDE version: 2023.2 Ultimate
- plugin version: the latest as of writing
- Elasticsearch or OpenSearch version: 5.6

**Comment by AntonShuvaev** [comment]
Hi @agntdv,  can you please provide the stacktrace from your `idea.log`. This can be found via `Help | Show Log in Finder` in the IDE. You can search for `Error while testing connection`.

**Comment by agntdv** [comment]
Hi, 

After checking the idea.log, I realized that in the "URL" field 'https://' was missing, all work fine now. 

Thanks.

Just in case the relevant fragment from the log:

2023-08-01 09:47:39,267 [62193225]   WARN - #org.elasticsearch4idea.kG - Error while testing connection
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.elasticsearch4idea.kp$j.invoke(SourceFile:306)
	at org.elasticsearch4idea.q.a(SourceFile:24)
	at org.elasticsearch4idea.q.b(SourceFile:49)
	at org.elasticsearch4idea.r$a.run(SourceFile:27)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 30 more
