### ISSUE TITLE
It seems the SSH connection stopped to work

### ISSUE THREAD

**Issue by an2riy** [AntonShuvaev/elasticsearch4idea#149]
The SSH connection stopped to work:
![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/8819844/05a3ad22-7b39-44b0-84f9-1407b9ecdf9f)
It complains about base64.

**Environment information:**
```
PhpStorm 2023.3.6
Build #PS-233.15026.12, built on March 21, 2024
Runtime version: 17.0.10+1-b1087.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-26-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 12
Registry:
  ide.main.menu.expand.horizontal=false
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=5b595c
  editor.focus.mode.color.dark=5b595c
  debugger.watches.in.variables=false
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  net.sjrx.intellij.plugins.systemdunitfiles (223.240127.136)
  de.femtopedia.diffplugin (2.1.12)
  com.nasller.CodeGlancePro (1.8.3)
  org.toml.lang (233.13135.67)
  com.jetbrains.space (233.15026.16)
  com.ultrahob.zerolength.plugin (0.95)
  org.elasticsearch4idea (2024.1.2-233)
  org.turbanov.run.configuration.as.action (2.2)
  com.intellij.properties (233.11799.172)
  String Manipulation (9.12.0)
  ir.msdehghan.plugins.ansible (0.92)
  de.achimonline.ansible_lint (1.6.2)
  indent-rainbow.indent-rainbow (2.2.0)
  com.intellij.grazie.pro (0.3.294)
  com.virtuslab.git-machete (4.2.0)
  com.intellij.bigdatatools.core (233.15026.9)
  com.intellij.bigdatatools.binary.files (233.11799.267)
  com.intellij.bigdatatools.rfs (233.15026.9)
  com.intellij.lang.jsgraphql (233.14808.14)
  com.magento.idea.magento2plugin (5.1.1)
  izhangzhihao.rainbow.brackets (2024.2.2-233)
  pro.bashsupport (4.0.1.233)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
  ru.adelf.idea.dotenv (2024.1)
  de.espend.idea.php.annotation (10.0.0)
  fr.adrienbrault.idea.symfony2plugin (2023.1.267)
  com.kalessil.phpStorm.phpInspectionsUltimate-mp (2024.1.1)
  org.sonarlint.idea (10.4.2.78113)
  mobi.hsz.idea.gitignore (4.5.2)
  com.github.blarc.gitlab-template-lint-plugin (1.13.2)
Current Desktop: ubuntu:GNOME

```

**Comment by AntonShuvaev** [comment]
Could you provide the logs related to this exception from `idea.log`? Please make sure to click the "Test Connection" button to generate the logs, not just the "Test SSH Connection".

**Comment by an2riy** [comment]
Hello.
See in the log only this:
```
2024-04-04 10:04:02,746 [  51329]   WARN - #org.elasticsearch4idea.lH - Error while testing connection
com.jcraft.jsch.JSchException: fromBase64: invalid base64 data
	at com.jcraft.jsch.Util.fromBase64(Util.java:77)
	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:257)
	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:58)
	at com.jcraft.jsch.JSch.setKnownHosts(JSch.java:405)
	at org.elasticsearch4idea.lX.a(SourceFile:36)
	at org.elasticsearch4idea.ln.a(SourceFile:166)
	at org.elasticsearch4idea.ln.a(SourceFile:74)
	at org.elasticsearch4idea.lk$g.a(SourceFile:63)
	at org.elasticsearch4idea.lk$g.invoke(SourceFile:62)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.elasticsearch4idea.lk.a(SourceFile:69)
	at org.elasticsearch4idea.lk.a(SourceFile:59)
	at org.elasticsearch4idea.lk$k.invoke(SourceFile:336)
	at org.elasticsearch4idea.q.a(SourceFile:24)
	at org.elasticsearch4idea.q.b(SourceFile:49)
	at org.elasticsearch4idea.r$a.run(SourceFile:27)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 78 out of bounds for length 78
	at com.jcraft.jsch.Util.fromBase64(Util.java:61)
	... 37 more
```

**Comment by an2riy** [comment]
It seems something with my **~/.ssh/known_hosts**, I can connect to any ssh server in the console but have the base64 error in the plugin after I removed **~/.ssh/known_hosts** I can connect now with the plugin.
