### ISSUE TITLE
java.lang.NoClassDefFoundError - in 0.2.0 and 0.1.9

### ISSUE THREAD

**Issue by Clanver** [AntonShuvaev/elasticsearch4idea#8]
Hi,

good job with the plugin first! 

Im not sure why, but  PHPStorm 2020.2 always reports IDE Fatal Errors in combination with your plugin.

Some of the tracktrace:

java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at org.elasticsearch4idea.model.ElasticsearchClusterInfo.toTableEntryList(ElasticsearchClusterInfo.kt:40)
	at org.elasticsearch4idea.ui.explorer.ElasticsearchExplorer$updateNodeInfo$1$1$1.run(ElasticsearchExplorer.kt:158)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)

I had hoped the update to version 0.2.0 would fix it, but i still get them. I will provide more information if the need arises of course! Maybe im missing something?

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for reporting this bug. The fix is ready and will be in 0.2.1.
