### ISSUE TITLE
Cannot open an index aliases and indexes

### ISSUE THREAD

**Issue by an2riy** [AntonShuvaev/elasticsearch4idea#83]
During a click on index aliases or indexes an issue appears:
![image](https://user-images.githubusercontent.com/8819844/184367592-0e1eb3b3-3e37-434d-b64d-5a2e32d80689.png)

Error:
```java.lang.UnsupportedOperationException
	at org.elasticsearch4idea.language.elasticsearch.b.getInputStream(ElasticsearchConsoleFile.kt:97)
	at com.a.a.s.a(SourceFile:121)
	at com.a.a.s.accept(SourceFile:111)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.lambda$getProviders$0(FileEditorProviderManagerImpl.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.lambda$getProviders$1(FileEditorProviderManagerImpl.java:52)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:143)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProviders(FileEditorProviderManagerImpl.java:52)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.canOpenFile(FileEditorManagerEx.java:103)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:925)
	at com.jetbrains.rdserver.fileEditors.BackendServerFileEditorManager.openFileImpl4(BackendServerFileEditorManager.kt:34)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:884)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:883)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:724)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:122)
	at org.elasticsearch4idea.jz.a(EditorUtils.kt:44)
	at org.elasticsearch4idea.jz.a(EditorUtils.kt:20)
	at org.elasticsearch4idea.dj.a(ElasticsearchExplorer.kt:404)
	at org.elasticsearch4idea.dj.b(ElasticsearchExplorer.kt:398)
	at org.elasticsearch4idea.dj.c(ElasticsearchExplorer.kt:354)
	at org.elasticsearch4idea.dj$1.onDoubleClick(ElasticsearchExplorer.kt:89)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:422)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

System info:
```
PhpStorm 2022.2
Build #PS-222.3345.135, built on July 28, 2022
Licensed to Andrii Dorotiuk
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-46-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    editor.caret.width=1
    ide.experimental.ui.navbar.scroll=true
    run.processes.with.pty=TRUE
    vcs.new.widget=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.3)
    pronskiy.elephpant (0.1.1)
    org.elasticsearch4idea (2022.2.0-222)
    name.kropp.intellij.makefile (222.3345.108)
    intellij-awk (0.3.2)
    indent-rainbow.indent-rainbow (2.0.2)
    de.femtopedia.diffplugin (2.1.8)
    com.ultrahob.zerolength.plugin (0.95)
    com.intellij.properties (222.3345.108)
    com.hjf.redis.manager.redis-manager (1.4.1)
    com.alayouni.ansiHighlight (22.2.2)
    String Manipulation (9.5.1)
    GrepConsole (12.14.211.6693.0)
    zielu.gittoolbox (212.9.7)
    uk.co.ben-gibson.remote.repository.mapper (4.1.8)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (65.1.0)
    com.majera.intellij.codereview.gitlab (2022.4.1.221)
    de.espend.idea.php.annotation (8.2.3)
    com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.5)
    com.magento.idea.magento2plugin (4.3.1)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
    izhangzhihao.rainbow.brackets (6.25)
    com.chrisrm.idea.MaterialThemeUI (7.7.1)
    ir.msdehghan.plugins.ansible (0.92)
    fr.adrienbrault.idea.symfony2plugin (2022.1.232)
    com.github.blarc.gitlab-template-lint-plugin (0.0.12)
    org.jetbrains.plugins.node-remote-interpreter (222.3345.108)
    ru.adelf.idea.dotenv (2022.2)
    pro.bashsupport (2.1.9.222)

Current Desktop: ubuntu:GNOME
```

**Comment by AntonShuvaev** [comment]
Hi, 

I found that the problem is caused by ANSI Highlighter Premium plugin. For some reason it tries to get inputstream of Elasticsearch plugin's file which is not physical file and doesn't provide inputstream. Please create an issue for ANSI Highlighter plugin, that it should not call `VirtualFile.getInputStream()` method for the unsupported files as it can throw`UnsupportedOperationException`.

**Comment by an2riy** [comment]
Thanks.
